version: '3.8'

services:
  app:
    build: .
    container_name: dental-clinic-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/dentaldb
      - SPRING_DATASOURCE_USERNAME=dentaluser
      - SPRING_DATASOURCE_PASSWORD=dentalpass
      - APP_JWT_SECRET=dentalcareluxurysecuresecretkey2026superstrongforproductiontokengeneration32bytes
    depends_on:
      - postgres
    restart: unless-stopped

  postgres:
    image: postgres:16-alpine
    container_name: dental-clinic-db
    environment:
      POSTGRES_DB: dentaldb
      POSTGRES_USER: dentaluser
      POSTGRES_PASSWORD: dentalpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
